import { HealthResponse } from "../lib/types";
import ModelBadge from "./ModelBadge";

interface FooterProps {
  health: HealthResponse | null;
}

export default function Footer({ health }: FooterProps) {
  return (
    <footer className="mt-12 pb-8">
      <hr className="double-rule max-w-lg mx-auto" />
      <div className="text-center space-y-3">
        {health && <ModelBadge health={health} />}
        <p className="text-sm text-[var(--color-text-muted)] font-[family-name:var(--font-lora)] italic">
          Predictions generated by an XGBoost model trained on 2025/26 season data.
          <br />
          Data sourced from the official Fantasy Premier League API.
        </p>
      </div>
    </footer>
  );
}
